version: '3.1'
services:
     db:
           image: postgres
           container_name: easyvms_db
           restart: always
           expose:
                - "5432"    
           networks:
                - mynet       
           environment:
                   POSTGRES_DB: easyvms
                   POSTGRES_USER: easyvms
                   POSTGRES_PASSWORD: easyvms123
                   PGDATA: /var/lib/postgresql/data/pgdata
     web:
             build:
                     context: .
                     args:
                        DATA_HOST: easyvms_db
                        DATA_USER: easyvms
                        DATA_DB: easyvms
                        DATA_PASS: easyvms123    
             ports:
               - "8050:8050"
             container_name: easyvms
             restart: always
             links:
                 - db
             tty: true      
             depends_on:
                     - db
             networks:
                     - mynet          
networks: 
     mynet: 
       driver: bridge    
